### ISSUE TITLE
SaveLoadState sample throws exception

### ISSUE THREAD

**Issue by ramtinak** [a-legotin/InstaSharper#99]
Hi, seems this sample throws exceptions too!

exception:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: User auth data must be specified
   at InstaSharper.API.Builder.InstaApiBuilder.Build() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper\API\Builder\InstaApiBuilder.cs:line 35
   at InstaSharper.Examples.Samples.SaveLoadState.<DoShow>d__2.MoveNext() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper.Examples\Samples\SaveLoadState.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at InstaSharper.Examples.Program.<MainAsync>d__2.MoveNext() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper.Examples\Program.cs:line 74
```

debug logs:

```
Press 1 to start basic demo samples
Press 2 to start upload photo demo sample
Press 3 to start comment media demo sample
Press 4 to start stories demo sample
Press 5 to start demo with saving state of API instance
Press 6 to start messaging demo sample
5

2:54 PM:        ----------------------------------------------------------------------------------------------------
2:54 PM:        Request: POST https://i.instagram.com/api/v1/accounts/current_user?edit=true
2:54 PM:        Headers:
2:54 PM:        Accept-Language:["en-US"]
2:54 PM:        X-IG-Capabilities:["3boBAA=="]
2:54 PM:        X-IG-Connection-Type:["WIFI"]
2:54 PM:        User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
2:54 PM:        Properties:
{
  "X-Google-AD-ID": "3cbd32f1-7e66-4f13-977a-f9bfca7cd388"
}
2:54 PM:        Response: POST https://i.instagram.com/api/v1/accounts/current_user/?edit=true
2:54 PM:        Content:
2:54 PM:        {"user": {"pk": 1647718432, "username": "soorenaapp", "full_name": "Soorena", "is_private": false, "profile_pic_url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s150x150/17661848_1892102291058005_5010980117095120896_a.jpg", "profile_pic_id": "1485608697707391560_1647718432", "is_verified": false, "has_anonymous_profile_picture": false, "biography": "Official Soorena", "external_url": "https://www.microsoft.com/en-in/store/p/soorena/9nblggh440d7", "external_lynx_url": "https://l.instagram.com/?u=https%3A%2F%2Fwww.microsoft.com%2Fen-in%2Fstore%2Fp%2Fsoorena%2F9nblggh440d7\u0026e=ATNC1NAY_4d62lS9h4-r5Zyj-PUC0Rs0XS1BZH052-oxdungX6iUxJVjFx_e2LfweQf3e4di", "hd_profile_pic_versions": [{"width": 320, "height": 320, "url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/s320x320/17661848_1892102291058005_5010980117095120896_a.jpg"}], "hd_profile_pic_url_info": {"url": "https://scontent-cdg2-1.cdninstagram.com/t51.2885-19/17661848_1892102291058005_5010980117095120896_a.jpg", "width": 439, "height": 439}, "show_conversion_edit_entry": true, "birthday": null, "phone_number": "+989174314006", "country_code": 98, "national_number": 9174314006, "gender": 1, "email": "ramtinjokar@outlook.com"}, "status": "ok"}
Got current user: soorenaapp using existing API instance
System.ArgumentNullException: Value cannot be null.
Parameter name: User auth data must be specified
   at InstaSharper.API.Builder.InstaApiBuilder.Build() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper\API\Builder\InstaApiBuilder.cs:line 35
   at InstaSharper.Examples.Samples.SaveLoadState.<DoShow>d__2.MoveNext() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper.Examples\Samples\SaveLoadState.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at InstaSharper.Examples.Program.<MainAsync>d__2.MoveNext() in F:\25-6\doc\Samples\InstaSharper-develop\InstaSharper.Examples\Program.cs:line 74
2:54 PM:        ----------------------------------------------------------------------------------------------------
2:54 PM:        Request: GET https://i.instagram.com/api/v1/accounts/logout/
2:54 PM:        Headers:
2:54 PM:        Accept-Language:["en-US"]
2:54 PM:        X-IG-Capabilities:["3boBAA=="]
2:54 PM:        X-IG-Connection-Type:["WIFI"]
2:54 PM:        User-Agent:["Instagram","12.0.0.7.91","Android","(23/6.0.1; 640dpi; 1440x2560; samsung; SM-G935F; hero2lte; samsungexynos8890; en_NZ)"]
2:54 PM:        Properties:
{
  "X-Google-AD-ID": "3cbd32f1-7e66-4f13-977a-f9bfca7cd388"
}
2:54 PM:        Response: GET https://i.instagram.com/api/v1/accounts/logout/
2:54 PM:        Content:
2:54 PM:        {"status": "ok"}
Logout succeed
```

**Comment by a-legotin** [comment]
fixed
